// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date': string;
  'element': string;
  'post': string;
  'titleRow': string;
}
export const cssExports: CssExports;
export default cssExports;
