// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'componentRoot': string;
  'date': string;
  'post': string;
  'title': string;
  'titleRow': string;
}
export const cssExports: CssExports;
export default cssExports;
