// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'right': string;
  'switch': string;
  'track': string;
}
export const cssExports: CssExports;
export default cssExports;
