// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'componentRoot': string;
  'title': string;
  'titleWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
