// This file is automatically generated.
// Do not manually edit this file!
interface CssExports {
  "componentRoot": string;
  "post": string;
  "title": string;
  "date": string;
}
export const cssExports: CssExports;
export default cssExports;