version: '3'


services:
  server:
    container_name: ${DOCKER_APP}-server
    env_file:
      - .env/${DOCKER_ENV}.env
    build:
      context: ./server/
      dockerfile: .docker/${DOCKER_ENV}.dockerfile
    volumes:
       - ./server/static:/var/www/static
       - ./server/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
    networks:
      - default


  client:
    container_name: ${DOCKER_APP}-client
    env_file:
      - .env/${DOCKER_ENV}.env
    build:
      context: ./client/
      dockerfile: .docker/${DOCKER_ENV}.dockerfile
    volumes:
       - ./client/:/var/www
    networks:
      - default


  api:
    container_name: ${DOCKER_APP}-api
    env_file:
      - .env/${DOCKER_ENV}.env
    build:
      context: ./api/
      dockerfile: .docker/${DOCKER_ENV}.dockerfile
    volumes:
       - ./api/:/var/www
       - /var/www/.venv
    networks:
      - default


networks:
  default:
    driver: bridge