packages:
  - "packages/compost"
  - "packages/e2e-hooks"
  - "packages/e2e"
  - "packages/eslint-config"
  - "packages/is"
  - "packages/posts"
  - "packages/preact-async"
  - "packages/preact-recoilless"
  - "packages/reading-time-cli"
  - "packages/recoilless"
  - "packages/scripts"
  - "packages/site"
  - "packages/utilities"
