packages:
  - 'packages/client'
  - 'packages/client-server'
  - 'packages/compost'
  - 'packages/e2e-hooks'
  - 'packages/e2e'
  - 'packages/eslint-config'
  - 'packages/posts'
  - 'packages/preact-recoilless'
  - 'packages/recoilless'
  - 'packages/scripts'
  - 'packages/utilities'
