// This file is automatically generated.
// Do not manually edit this file!
interface CssExports {
  "componentRoot": string;
  "track": string;
  "switch": string;
  "right": string;
  "icon": string;
}
export const cssExports: CssExports;
export default cssExports;