// This file is automatically generated.
// Do not manually edit this file!
declare const classes: {
  readonly componentRoot: string;
  readonly track: string;
  readonly switch: string;
  readonly right: string;
  readonly icon: string;
};
export default classes;
export { classes };
