// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backgroundImage': string;
  'componentRoot': string;
  'content': string;
  'show': string;
}
export const cssExports: CssExports;
export default cssExports;
