// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bath': string;
  'blackTusk': string;
  'christmasTrail': string;
  'crabappleDrive': string;
  'englishBayPark': string;
  'fagus': string;
  'greatNorthernHighway': string;
  'greenLake': string;
  'harmonyRidge': string;
  'jerseyCream': string;
  'kew': string;
  'lionsGateBridge': string;
  'nullarbor': string;
  'rainbowPark': string;
  'royalExhibitionHall': string;
  'ship': string;
  'sydney': string;
  'sydneyHarbourBridge': string;
  'tree': string;
}
export const cssExports: CssExports;
export default cssExports;
