// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appear': string;
  'appearActive': string;
  'appearDone': string;
  'backgroundImage': string;
  'componentRoot': string;
  'content': string;
  'enter': string;
  'enterActive': string;
  'enterDone': string;
  'exit': string;
  'exitActive': string;
  'exitDone': string;
}
export const cssExports: CssExports;
export default cssExports;
