// This file is automatically generated.
// Do not manually edit this file!
declare const classes: {
  readonly componentRoot: string;
  readonly content: string;
  readonly transparentIn: string;
  readonly opaque: string;
  readonly transparentOut: string;
  readonly backgroundPicture: string;
  readonly backgroundImage: string;
};
export default classes;
export { classes };
