// This file is automatically generated.
// Do not manually edit this file!
interface CssExports {
  "componentRoot": string;
  "content": string;
  "transparentIn": string;
  "opaque": string;
  "transparentOut": string;
  "backgroundPicture": string;
  "backgroundImage": string;
}
export const cssExports: CssExports;
export default cssExports;