// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backgroundImage': string;
  'backgroundPicture': string;
  'componentRoot': string;
  'content': string;
  'opaque': string;
  'transparentIn': string;
  'transparentOut': string;
}
export const cssExports: CssExports;
export default cssExports;
