// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'componentRoot': string;
  'footer': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
