// This file is automatically generated.
// Do not manually edit this file!
declare const classes: {
  readonly componentRoot: string;
  readonly link: string;
  readonly active: string;
  readonly optionsList: string;
  readonly menuButton: string;
  readonly dismissBox: string;
  readonly open: string;
};
export default classes;
export { classes };
