// This file is automatically generated.
// Do not manually edit this file!
interface CssExports {
  "componentRoot": string;
  "link": string;
  "active": string;
  "optionsList": string;
  "menuButton": string;
  "dismissBox": string;
  "open": string;
}
export const cssExports: CssExports;
export default cssExports;