// This file is automatically generated.
// Do not manually edit this file!
declare const classes: {
  readonly componentRoot: string;
  readonly title: string;
  readonly metaDataRow: string;
  readonly article: string;
  readonly date: string;
};
export default classes;
export { classes };
