version: 2.1

src-dir: &src-dir ~/src

base: &base
  docker:
    - image: node:16.13.0
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD

  working_directory: *src-dir

jobs:
  checkout-install-build:
    <<: *base

    steps:
      - checkout:
          path: *src-dir

      # # Deps for image-webpack-loader
      # - run: sudo apt-get update && sudo apt-get install nasm libjpeg-dev

      - run: npm i -g pnpm@6.19.0
      - run: pnpm install --filter \"!@jaybeeuu/e2e\"
      - run: pnpm build
      - run: pnpm gen-certs
      - store_artifacts:
          path: ./packages/site/dist
          destination: site-dist
      - persist_to_workspace:
          root: *src-dir
          paths:
            - ./*

  lint:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: npm i -g pnpm@6.19.0
      - run: pnpm lint

  spellcheck:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: npm i -g pnpm@6.19.0
      - run: pnpm spellcheck

  type-check:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: npm i -g pnpm@6.19.0
      - run: pnpm type-check

  test:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: npm i -g pnpm@6.19.0
      - run: pnpm test

  e2e:
    <<: *base
    docker:
      - image: cypress/included:8.6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    working_directory: *src-dir

    steps:
      - attach_workspace:
          at: *src-dir
      - run: npm i -g pnpm@6.19.0 wait-on
      - run: pnpm e2e-ci
      - store_artifacts:
          path: ./packages/e2e/.screenshots
          destination: e2e-screenshots
      - store_artifacts:
          path: ./packages/e2e/.videos
          destination: e2e-videos

workflows:
  version: 2

  install-build-test:
    jobs:
      - checkout-install-build

      - lint:
          requires:
            - checkout-install-build
      - spellcheck:
          requires:
            - checkout-install-build
      - type-check:
          requires:
            - checkout-install-build
      - test:
          requires:
            - checkout-install-build
      - e2e:
          requires:
            - checkout-install-build
