version: 2.1

docker-image-node: &docker-image-node

src-dir: &src-dir ~/src

base: &base
  docker:
    - image: circleci/node:12.18.0
  environment:
    - CYPRESS_CACHE_FOLDER: ./.cache/Cypress

  working_directory: *src-dir

jobs:
  checkout-install-build:
    <<: *base

    steps:
      - checkout:
          path: *src-dir

      - run: sudo npm install -g pnpm@^5.4.0
      - run: pnpm run bootstrap
      - run: npm run build
      - run: pnpm run gen-certs
      - store_artifacts:
          path: ./packages/client/dist
          destination: client-dist
      - persist_to_workspace:
          root: *src-dir
          paths:
            - ./*

  lint:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: sudo npm install -g pnpm@^5.4.0
      - run: pnpm run lint


  type-check:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: sudo npm install -g pnpm@^5.4.0
      - run: pnpm run type-check

  test:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: sudo npm install -g pnpm@^5.4.0
      - run: pnpm run test

  e2e:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: sudo npm install -g pnpm@^5.4.0 wait-on
      - run: ls packages/client/certs
      - run: cat packages/client/certs/cert.crt
      - run: cat packages/client/certs/key.key
      - run: cat packages/client/certs/ca.pem
      - run: npm run e2e:ci

workflows:
  version: 2

  install-build-test:
    jobs:
      - checkout-install-build

      # - lint:
      #     requires:
      #       - checkout-install-build
      # - type-check:
      #     requires:
      #       - checkout-install-build
      # - test:
      #     requires:
      #       - checkout-install-build
      - e2e:
          requires:
            - checkout-install-build
