version: 2.1

docker-image-node: &docker-image-node
    docker:
      - image: circleci/node:12.13.1

src-dir: &src-dir ~/src

api-base: &api-base
    <<: *docker-image-node

    working_directory: ~/src/api

jobs:
    api-checkout-install:
        <<: *api-base

        steps:
          - checkout:
              path: *src-dir

          - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  - v1-dependencies-

          - run: npm install

          - save_cache:
               paths:
                 - node_modules
               key: v1-dependencies-{{ checksum "package.json" }}

          - run: ./scripts/post-create-command.sh

          - persist_to_workspace:
                root: *src-dir
                paths:
                  - ./*


    api-type-check:
        <<: *api-base

        steps:
          - attach_workspace:
                at: *src-dir

          - run: npm run-script type-check


    api-test:
        <<: *api-base

        steps:
          - attach_workspace:
                at: *src-dir

          - run: npm run-script test


    api-lint:
        <<: *api-base

        steps:
          - attach_workspace:
                at: *src-dir

          - run: npm run-script lint


    api-build:
        <<: *api-base

        steps:
          - attach_workspace:
                at: *src-dir

          - run: npm run-script build

          - store_artifacts:
              path: ./dist
              destination: api-dist


workflows:
  version: 2

  api-install-test:
    jobs:
      - api-checkout-install
      - api-type-check:
            requires:
              - api-checkout-install
      - api-test:
            requires:
              - api-checkout-install
      - api-lint:
            requires:
              - api-checkout-install
      - api-build:
            requires:
              - api-checkout-install

    #   - api-lint
    #   - api-test
    #   - api-build