version: 2.1

src-dir: &src-dir ~/src

install-pnpm: &install-pnpm npm i -g pnpm@7.0.0

base: &base
  docker:
    - image: cimg/node:16.15.1
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD

  working_directory: *src-dir

jobs:
  checkout-install-build:
    <<: *base

    steps:
      - checkout:
          path: *src-dir

      - run: *install-pnpm
      - run: pnpm -r install
      - run: pnpm build
      - run: pnpm gen-certs
      - store_artifacts:
          path: ./packages/site/dist
          destination: site-dist
      - persist_to_workspace:
          root: *src-dir
          paths:
            - ./*

  lint:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: *install-pnpm
      - run: pnpm lint

  spellcheck:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: *install-pnpm
      - run: pnpm spellcheck

  type-check:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: *install-pnpm
      - run: pnpm type-check

  test:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: *install-pnpm
      - run: pnpm test

  e2e:
    <<: *base
    docker:
      - image: cypress/included:10.2.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    working_directory: *src-dir

    steps:
      - attach_workspace:
          at: *src-dir
      - run: *install-pnpm
      - run: pnpm e2e-ci
      - store_artifacts:
          path: ./packages/e2e/.screenshots
          destination: e2e-screenshots
      - store_artifacts:
          path: ./packages/e2e/.videos
          destination: e2e-videos

workflows:
  version: 2

  install-build-test:
    jobs:
      - checkout-install-build

      - lint:
          requires:
            - checkout-install-build
      - spellcheck:
          requires:
            - checkout-install-build
      - type-check:
          requires:
            - checkout-install-build
      - test:
          requires:
            - checkout-install-build
      - e2e:
          requires:
            - checkout-install-build
