version: 2.1

src-dir: &src-dir ~/src

base: &base
  docker:
    - image: circleci/node:12.18.3

  working_directory: *src-dir

jobs:
  checkout-install-build:
    <<: *base

    steps:
      - checkout:
          path: *src-dir

      - run: npm install --no-package-lock pnpm@^5.5.2 wait-on
      - run: npm run bootstrap
      - run: npm run build
      - run: npm run gen-certs
      - store_artifacts:
          path: ./packages/client/dist
          destination: client-dist
      - persist_to_workspace:
          root: *src-dir
          paths:
            - ./*

  lint:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: npm run lint


  type-check:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: npm run type-check

  test:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: npm run test

  e2e:
    <<: *base
    docker:
      - image: cypress/browsers:node12.18.0-chrome83-ff77

    working_directory: *src-dir

    steps:
      - attach_workspace:
          at: *src-dir
      # Persisting the Cypress binaries in the workspace adds a lot of time to the jobs attaching.
      # So allow it to be lost after the install step and install it again here.
      - run: npm run e2e -- install
      - run: npm run e2e-ci

workflows:
  version: 2

  install-build-test:
    jobs:
      - checkout-install-build

      - lint:
          requires:
            - checkout-install-build
      - type-check:
          requires:
            - checkout-install-build
      - test:
          requires:
            - checkout-install-build
      - e2e:
          requires:
            - checkout-install-build
