version: 2.1

docker-image-node: &docker-image-node
    docker:
      - image: circleci/node:12.13.1

src-dir: &src-dir ~/src

api-base: &api-base
    <<: *docker-image-node

    working_directory: ~/src/api

jobs:
    checkout:
        <<: *docker-image-node

        working_directory: ~/src

        steps:
          - checkout:
              path: *src-dir

          - run: ./.devcontainer/scripts/post-create-command.sh

          - persist_to_workspace:
              root: *src-dir
              paths:
                - ./*


    api-install-deps:
        <<: *api-base

        steps:
          - attach_workspace:
                at: *src-dir

          - restore_cache:
                keys:
                  - v1-npm-deps-{{ checksum "./api/package-lock.json" }}
                  - v1-npm-deps

          - run: npm install

          - save_cache:
               paths:
                 - node_modules
               key: v1-npm-deps-{{ checksum "./api/package-lock.json" }}



    api-type-check:
        <<: *api-base

        steps:
          - attach_workspace:
                at: *src-dir

          - run: npm run-script type-check


    api-test:
        <<: *api-base

        steps:
          - attach_workspace:
                at: *src-dir

          - run: npm run-script test


    api-lint:
        <<: *api-base

        steps:
          - attach_workspace:
                at: *src-dir

          - run: npm run-script lint


    api-build:
        <<: *api-base

        steps:
          - attach_workspace:
                at: *src-dir

          - run: npm run-script build

          - store_artifacts:
              path: ./dist
              destination: api-dist


workflows:
  version: 2

  api-install-test:
    jobs:
      - checkout

      - api-install-deps:
            requires:
              - checkout
      - api-type-check:
            requires:
              - api-install-deps
      - api-test:
            requires:
              - api-install-deps
      - api-lint:
            requires:
              - api-install-deps
      - api-build:
            requires:
              - api-install-deps

    #   - api-lint
    #   - api-test
    #   - api-build