version: 2.1

docker-image-node: &docker-image-node

src-dir: &src-dir ~/src

base: &base
  docker:
    - image: circleci/node:12.18.0

  working_directory: *src-dir

jobs:
  checkout-install-deps:
    <<: *base

    steps:
      - checkout:
          path: *src-dir

      - run: sudo npm install -g pnpm@^5.4.0
      - run: pnpm run bootstrap

      - persist_to_workspace:
          root: *src-dir
          paths:
            - ./*

  build:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: pnpm run build
      - run: pnpm run gen-certs
      - store_artifacts:
          path: ./packages/client/dist
          destination: client-dist

      - persist_to_workspace:
          root: *src-dir
          paths:
            - ./*


  lint:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: pnpm run lint


  type-check:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: pnpm run type-check


  test:
    <<: *base

    steps:
      - attach_workspace:
          at: *src-dir
      - run: pnpm run test


workflows:
  version: 2

  install-test-build:
    jobs:
      - checkout-install-deps

      - build:
          requires:
            - checkout-install-deps
      - lint:
          requires:
             - checkout-install-deps

      - type-check:
          requires:
            - build
      - test:
          requires:
            - build
