// This file is automatically generated.
// Do not manually edit this file!
interface CssExports {
  "componentRoot": string;
  "main": string;
  "static": string;
}
export const cssExports: CssExports;
export default cssExports;