// This file is automatically generated.
// Do not manually edit this file!
declare const classes: {
  readonly componentRoot: string;
  readonly main: string;
  readonly static: string;
};
export default classes;
export { classes };
