// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'heading': string;
  'paragraph': string;
}
export const cssExports: CssExports;
export default cssExports;
